copy .\jtcps1.rbf "1941 Counter Attack.np1" 
copy .\jtcps1.rbf "Captain Commando.np1" 
copy .\jtcps1.rbf "Carrier Air Wing.np1" 
copy .\jtcps1.rbf "Dynasty Wars.np1" 
copy .\jtcps1.rbf "Final Fight.np1" 
copy .\jtcps1.rbf "Forgotten Worlds.np1" 
copy .\jtcps1.rbf "Ghouls n Ghosts.np1" 
copy .\jtcps1.rbf "Knights of the Round.np1" 
copy .\jtcps1.rbf "Magic Sword.np1" 
copy .\jtcps1.rbf "Mega Man.np1" 
copy .\jtcps1.rbf "Mega Twins.np1" 
copy .\jtcps1.rbf "Mercs.np1" 
copy .\jtcps1.rbf "Nemo.np1" 
copy .\jtcps1.rbf "Pang 3.np1" 
copy .\jtcps1.rbf "Pnickies.np1" 
copy .\jtcps1.rbf "Pokonyan Balloon.np1" 
copy .\jtcps1.rbf "Quiz and Dragons.np1" 
copy .\jtcps1.rbf "SF Alpha Warriors Dreams.np1" 
copy .\jtcps1.rbf "SF Zero.np1" 
copy .\jtcps1.rbf "SF2 Champion Edition.np1" 
copy .\jtcps1.rbf "SF2 Hyper Fighting.np1" 
copy .\jtcps1.rbf "SF2 The World Warrior.np1" 
copy .\jtcps1.rbf "SF2 Turbo Hyper Fighting.np1" 
copy .\jtcps1.rbf "Strider.np1" 
copy .\jtcps1.rbf "The King of Dragons.np1" 
copy .\jtcps1.rbf "Three Wonders.np1" 
copy .\jtcps1.rbf "UN Squadron.np1" 
copy .\jtcps1.rbf "Varth.np1" 
copy .\jtcps1.rbf "Warriors of Fate.np1" 
copy .\jtcps1.rbf "Willow.np1" 
